$("#toggleLeft").click(function(){
        $("#myCarousel").fadeOut(1000);
        $(".gallery").hide();
        $(".other").show();
        $("#myCarousel4").fadeIn(1500);
      });
      $("#toggleLeft2").click(function(){
        $("#myCarousel1").fadeOut(1000);
        $(".productionStills").hide();
        $(".gallery").show();
        $("#myCarousel").fadeIn(1500);
      });
      $("#toggleLeft3").click(function(){
        $("#myCarousel2").fadeOut(1000);
        $(".physique").hide();
        $(".productionStills").show();
        $("#myCarousel1").fadeIn(1500);
      });
        $("#toggleLeft4").click(function(){
        $("#myCarousel3").fadeOut(1000);
        $(".fullScene").hide();
        $(".physique").show();
        $("#myCarousel2").fadeIn(1500);
      });
        $("#toggleLeft5").click(function(){
        $("#myCarousel4").fadeOut(1000);
        $(".other").hide();
        $(".fullScene").show();
        $("#myCarousel3").fadeIn(1500);
      });
      $("#toggleRight").click(function(){
          $("#myCarousel").fadeOut(1000);
          $(".gallery").hide();
          $(".productionStills").show();
          $("#myCarousel1").fadeIn(1500);
      });
      $("#toggleRight2").click(function(){
        $("#myCarousel1").fadeOut(1000);
        $(".productionStills").hide();
        $(".physique").show();
        $("#myCarousel2").fadeIn(1500);
      });
      $("#toggleRight3").click(function(){
        $("#myCarousel2").fadeOut(1000);
        $(".physique").hide();
        $(".fullScene").show();
        $("#myCarousel3").fadeIn(1500);
      });
         $("#toggleRight4").click(function(){
        $("#myCarousel3").fadeOut(1000);
        $(".fullScene").hide();
        $(".other").show();
        $("#myCarousel4").fadeIn(1500);
      });
        $("#toggleRight5").click(function(){
        $("#myCarousel4").fadeOut(1000);
        $(".other").hide();
        $(".gallery").show();
        $("#myCarousel").fadeIn(1500);
      });
